apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: streamingapp
type: Opaque
stringData:
  JWT_SECRET: "changeme"
  AWS_ACCESS_KEY_ID: "<your-access-key>"
  AWS_SECRET_ACCESS_KEY: "<your-secret-key>"
